/**
 * /scripts/blog/demos/graflect-data.js
 * * Contains all the default data maps for the Graflect system.
 * This file should be loaded before any other script that uses this data,
 * such as dictionary-manager.js, graflect.js, or romaji.js.
 */

// This is the canonical default word map, taken from romaji.js.
const defaultWordMap = { 'a': '', 'an': '', 'and': '', 'are': '', 'as': '', 'at': '', 'be': '', 'because': '', 'been': '', 'before': '', 'but': '', 'by': '', 'call': '', 'can': '', 'change': '', 'come': '', 'could': '', 'day': '', 'do': '', 'down': '', 'each': '', 'even': '', 'first': '', 'find': '', 'for': '', 'from': '', 'get': '', 'give': '', 'go': '', 'good': '', 'great': '', 'had': '', 'has': '', 'have': '', 'he': '', 'her': '', 'here': '', 'him': '', 'his': '', 'how': '', 'i': '', 'if': '', 'in': '', 'into': '', 'is': '', 'it': '', 'its': '', 'just': '', 'know': '', 'like': '', 'long': '', 'look': '', 'made': '', 'make': '', 'man': '', 'may': '', 'me': '', 'more': '', 'most': '', 'my': '', 'new': '', 'not': '', 'now': '', 'of': '', 'on': '', 'one': '', 'only': '', 'or': '', 'other': '', 'out': '', 'over': '', 'people': '', 'place': '', 'said': '', 'same': '', 'see': '', 'she': '', 'so': '', 'some': '', 'take': '', 'than': '', 'that': '', 'the': '', 'their': '', 'them': '', 'then': '', 'there': '', 'these': '', 'they': '', 'thing': '', 'think': '', 'this': '', 'those': '', 'time': '', 'to': '', 'two': '', 'up': '', 'use': '', 'very': '', 'want': '', 'was': '', 'water': '', 'way': '', 'we': '', 'well': '', 'were': '', 'what': '', 'when': '', 'where': '', 'which': '', 'who': '', 'why': '', 'will': '', 'with': '', 'work': '', 'would': '', 'year': '', 'you': '', 'your': '', 'own': '', 'also': '', 'about': '', 'came': '', 'house': '', 'road': '', 'did': '', 'ball': '', 'session': '', 'all': '' };

// This is the shared pool of vowel sounds.
const vowelPool = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''];

// This is the canonical default grapheme map, taken from romaji.js.
const defaultGraphemeMap = { 'tious': '', 'cious': '', 'ssion': '', 'stle': '', 'sion': ['', ''], 'tion': '', 'cian': '', 'tial': '', 'cial': '', 'sure': '', 'ture': '', 'dge': '', 'eigh': '', 'igh': '', 'tch': '', 'age': ['', ''], 'ex': ['', '', '', ''], 'nge': '', 'que': '', 'lk': '', 'lm': '', 'mb': '', 'bt': '', 'ps': '', 'pn': '', 'rh': '', 'sch': ['', ''], 'sci': ['', ''], 'eau': ['', ''], 'sc': ['', ''], 'gu': ['', ''], 'ck': '', 'qu': '', 'th': ['', ''], 'sh': '', 'ch': ['', '', '', ''], 'ng': '', 'ph': '', 'kn': '', 'wr': '', 'gh': ['', '', ''], 'oo': ['', '', ''], 'ee': ['', ''], 'ea': ['', '', ''], 'ou': ['', '', '', ''], 'ow': ['', '', ''], 'ew': ['', ''], 'au': '', 'oi': '', 'oy': '', 'ai': ['', ''], 'ay': '', 'll': '', 'ss': ['', ''], 'ff': '', 'rr': '', 'pp': '', 'bb': '', 'dd': '', 'tt': '', 'mm': '', 'nn': '', 'a': ['', '', '', '', ''], 'e': ['', '', ''], 'i': ['', '', ''], 'o': ['', '', '', '', ''], 'u': ['', '', '', ''], 'y': ['', '', ''], 's': ['', ''], 'g': ['', ''], 'c': ['', ''], 'x': ['', ''], 'p': '', 'b': '', 't': '', 'h': ['', ''], 'l': '', 'w': '', 'r': ['', '', '', ''], 'j': '', 'd': '', 'f': '', 'k': '', 'm': '', 'n': '', 'v': '', 'z': '', 'tr': '' };

// This is the shared map for converting Graflect characters to a readable "slug".
const slugMap = { '': 'p', '': 'b', '': 't', '': 'd', '': 'k', '': 'g', '': 'f', '': 'v', '': 'th', '': 'dh', '': 's', '': 'z', '': 'š', '': 'ž', '': 'h', '': 'm', '': 'n', '': 'ng', '': 'l', '': 'r', '': 'w', '': 'y', '': 'ī', '': 'i', '': 'u', '': 'ü', '': 'e', '': 'æ', '': 'x', '': 'á', '': 'ē', '': 'ä', '': 'ai', '': 'ow', '': 'ō', '': 'õ', '': 'ö', '': '4', '': 'c', '': 'j', '': 'yü', '': 'wī', '': 'yh', '': 'kh', '': 'rr', '': 'rh', '' : 'rä', '': ' ' };
